version: '3.3'
services:
  backend:
    build: ./fire-image-backend/
    ports:
      - "8000:80"
  frontend:
    build: 
      context: ./fire-image-frontend/
      args:
        - NEXT_PUBLIC_BACKEND_SERVICE_IP=${NEXT_PUBLIC_BACKEND_SERVICE_IP}
    ports:
      - "8080:3000"
    